---
# Simplified OpenTelemetry Demo for EDOT

apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-demo-instrumentation
  namespace: otel-demo
spec:
  exporter:
    endpoint: https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443
  env:
    - name: OTEL_EXPORTER_OTLP_HEADERS
      value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  java:
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: "false"
  nodejs:
    env:
      - name: OTEL_NODEJS_DEBUG
        value: "false"
  python:
    env:
      - name: OTEL_PYTHON_LOG_LEVEL
        value: "info"
  dotnet:
    env:
      - name: OTEL_DOTNET_AUTO_LOG_DIRECTORY
        value: "/tmp"
---
# Redis for Cart Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: otel-demo
spec:
  selector:
    app: redis-cart
  ports:
  - port: 6379
---
# Ad Service (Java) - Auto-instrumentation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: adservice
        image: ghcr.io/open-telemetry/demo:1.11.1-adservice
        ports:
        - containerPort: 8080
        env:
        - name: AD_SERVICE_PORT
          value: "8080"
        - name: OTEL_SERVICE_NAME
          value: "adservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: otel-demo
spec:
  selector:
    app: adservice
  ports:
  - port: 8080
---
---
# Cart Service (.NET) - Auto-instrumentation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
    spec:
      containers:
      - name: cartservice
        image: ghcr.io/open-telemetry/demo:1.11.1-cartservice
        ports:
        - containerPort: 8080
        env:
        - name: VALKEY_ADDR  # Changed from REDIS_ADDR
          value: "redis-cart:6379"
        - name: REDIS_ADDR   # Keep for backward compatibility
          value: "redis-cart:6379"
        - name: CART_SERVICE_PORT
          value: "8080"
        - name: ASPNETCORE_URLS
          value: "http://*:8080"
        - name: OTEL_SERVICE_NAME
          value: "cartservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: otel-demo
spec:
  selector:
    app: cartservice
  ports:
  - port: 8080
---
# Currency Service (C++) - Built-in SDK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: currencyservice
        image: ghcr.io/open-telemetry/demo:1.11.1-currencyservice
        ports:
        - containerPort: 8080
        env:
        - name: CURRENCY_SERVICE_PORT
          value: "8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
        - name: OTEL_SERVICE_NAME
          value: "currencyservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: otel-demo
spec:
  selector:
    app: currencyservice
  ports:
  - port: 8080
---
# Email Service (Ruby) - Built-in SDK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: emailservice
        image: ghcr.io/open-telemetry/demo:1.11.1-emailservice
        ports:
        - containerPort: 8080
        env:
        - name: EMAIL_SERVICE_PORT
          value: "8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
        - name: OTEL_SERVICE_NAME
          value: "emailservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  namespace: otel-demo
spec:
  selector:
    app: emailservice
  ports:
  - port: 8080
---
# Payment Service (Node.js) - Auto-instrumentation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
    spec:
      containers:
      - name: paymentservice
        image: ghcr.io/open-telemetry/demo:1.11.1-paymentservice
        ports:
        - containerPort: 8080
        env:
        - name: PAYMENT_SERVICE_PORT
          value: "8080"
        - name: OTEL_SERVICE_NAME
          value: "paymentservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: otel-demo
spec:
  selector:
    app: paymentservice
  ports:
  - port: 8080
---
# Product Catalog Service (Go) - Built-in SDK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - name: productcatalogservice
        image: ghcr.io/open-telemetry/demo:1.11.1-productcatalogservice
        ports:
        - containerPort: 8080
        env:
        - name: PRODUCT_CATALOG_SERVICE_PORT
          value: "8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
        - name: OTEL_SERVICE_NAME
          value: "productcatalogservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: otel-demo
spec:
  selector:
    app: productcatalogservice
  ports:
  - port: 8080
---
# Recommendation Service (Python) - Auto-instrumentation
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: recommendationservice
        image: ghcr.io/open-telemetry/demo:1.11.1-recommendationservice
        ports:
        - containerPort: 8080
        env:
        - name: RECOMMENDATION_SERVICE_PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:8080"
        - name: OTEL_SERVICE_NAME
          value: "recommendationservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: "python"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: otel-demo
spec:
  selector:
    app: recommendationservice
  ports:
  - port: 8080
---
# Quote Service (PHP) - Built-in SDK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoteservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quoteservice
  template:
    metadata:
      labels:
        app: quoteservice
    spec:
      containers:
      - name: quoteservice
        image: ghcr.io/open-telemetry/demo:1.11.1-quoteservice
        ports:
        - containerPort: 8080
        env:
        - name: QUOTE_SERVICE_PORT
          value: "8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
        - name: OTEL_SERVICE_NAME
          value: "quoteservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
        - name: OTEL_PHP_AUTOLOAD_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: quoteservice
  namespace: otel-demo
spec:
  selector:
    app: quoteservice
  ports:
  - port: 8080
---
# Shipping Service (Rust) - Built-in SDK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: shippingservice
        image: ghcr.io/open-telemetry/demo:1.11.1-shippingservice
        ports:
        - containerPort: 8080
        env:
        - name: SHIPPING_SERVICE_PORT
          value: "8080"
        - name: QUOTE_SERVICE_ADDR
          value: "http://quoteservice:8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
        - name: OTEL_SERVICE_NAME
          value: "shippingservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  namespace: otel-demo
spec:
  selector:
    app: shippingservice
  ports:
  - port: 8080
---
# Checkout Service (Go) - Built-in SDK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - name: checkoutservice
        image: ghcr.io/open-telemetry/demo:1.11.1-checkoutservice
        ports:
        - containerPort: 8080
        env:
        - name: CHECKOUT_SERVICE_PORT
          value: "8080"
        - name: CART_SERVICE_ADDR
          value: "cartservice:8080"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:8080"
        - name: EMAIL_SERVICE_ADDR
          value: "emailservice:8080"
        - name: PAYMENT_SERVICE_ADDR
          value: "paymentservice:8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
        - name: OTEL_SERVICE_NAME
          value: "checkoutservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: otel-demo
spec:
  selector:
    app: checkoutservice
  ports:
  - port: 8080
---
# Frontend (Go) - Built-in SDK
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/open-telemetry/demo:1.11.1-frontend
        ports:
        - containerPort: 8080
        env:
        - name: FRONTEND_ADDR
          value: ":8080"
        - name: AD_SERVICE_ADDR
          value: "adservice:8080"
        - name: CART_SERVICE_ADDR
          value: "cartservice:8080"
        - name: CHECKOUT_SERVICE_ADDR
          value: "checkoutservice:8080"
        - name: CURRENCY_SERVICE_ADDR
          value: "currencyservice:8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:8080"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendationservice:8080"
        - name: SHIPPING_SERVICE_ADDR
          value: "shippingservice:8080"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "https://your-elastic-endpoint.apm.us-east-2.aws.elastic-cloud.com:443"
        - name: OTEL_EXPORTER_OTLP_HEADERS
          value: "Authorization=Bearer xxxyyyyyzzzzzqqqqrrrss"
        - name: OTEL_SERVICE_NAME
          value: "frontend"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
        - name: ENV_PLATFORM
          value: "openshift"
        - name: OTEL_COLLECTOR_NAME
          value: "elastic-apm"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: otel-demo
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  namespace: otel-demo
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
---
# Load Generator (Python) - Auto-instrumentation + Generates Traffic
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
    spec:
      containers:
      - name: loadgenerator
        image: ghcr.io/open-telemetry/demo:1.11.1-loadgenerator
        env:
        - name: FRONTEND_ADDR
          value: "frontend:8080"
        - name: LOCUST_WEB_PORT
          value: "8089"
        - name: LOCUST_USERS
          value: "5"
        - name: LOCUST_SPAWN_RATE
          value: "1"
        - name: LOCUST_HOST
          value: "http://frontend:8080"
        - name: LOCUST_HEADLESS
          value: "false"
        - name: LOCUST_AUTOSTART
          value: "true"
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: "python"
        - name: OTEL_SERVICE_NAME
          value: "loadgenerator"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=otel-demo"
